version: "3.3"

services:

  traefik:
    image: "traefik:v2.4"
    container_name: "traefik"
    command:
      - "--api=false"
      - "--certificatesresolvers.myresolver.acme.httpchallenge.entrypoint=web"
      - "--certificatesresolvers.myresolver.acme.storage=/etc/traefik/acme.json"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.web.http.redirections.entryPoint.permanent=true"
      - "--entrypoints.web.http.redirections.entryPoint.scheme=https"
      - "--entrypoints.web.http.redirections.entryPoint.to=websecure"
      - "--entrypoints.websecure.address=:443"
      - "--providers.docker.exposedbydefault=false"
      - "--providers.docker=true"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "traefik-data:/etc/traefik"

  registry:
    image: "registry:2"
    container_name: "registry"
    labels:
      - "traefik.enable=true"
      - "traefik.http.middlewares.registry-auth.basicauth.users=${REGISTRY_USERS:-admin:$2y$05$TQ01MQmBS.BsgoCEhENWuOB/hF3gW3GKd/JiVWMWaf3hX0Wrhin4i}"
      - "traefik.http.routers.registry.entrypoints=websecure"
      - "traefik.http.routers.registry.middlewares=registry-auth"
      - "traefik.http.routers.registry.rule=Host(`${REGISTRY_URL:-registry.example.com}`)"
      - "traefik.http.routers.registry.tls.certresolver=myresolver"
      - "traefik.http.routers.registry.tls=true"
    volumes:
      - "registry-data:/var/lib/registry"

  registry-browser:
    image: "klausmeyer/docker-registry-browser"
    container_name: "registry-browser"
    labels:
      - 'traefik.http.middlewares.browser-stripprefix.stripprefix.prefixes=/browser'
      - "traefik.enable=true"
      - "traefik.http.routers.registry-browser.entrypoints=websecure"
      - "traefik.http.routers.registry-browser.rule=Host(`${REGISTRY_URL:-registry.example.com}`) && PathPrefix(`/browser`)"
      - "traefik.http.routers.registry-browser.tls.certresolver=myresolver"
      - "traefik.http.routers.registry-browser.tls=true"
      - "traefik.http.routers.registry-browser.middlewares=registry-auth,browser-stripprefix"
    depends_on:
      - registry
    environment:
      SCRIPT_NAME: "/browser"
      RAILS_RELATIVE_URL_ROOT: "/browser"
      DOCKER_REGISTRY_URL: "http://registry:5000"
      PUBLIC_REGISTRY_URL: "${REGISTRY_URL:-registry.example.com}"

volumes:
  traefik-data:
  registry-data: