version: "3.8"

services:

  minio:
    image: "minio/minio"
    deploy:
      labels:
        - traefik.enable=true
        - traefik.docker.network=traefik-public
        - traefik.constraint-label=traefik-public
        - traefik.http.routers.minio.entrypoints=websecure
        - traefik.http.routers.minio.rule=Host(`${MINIO_URL:-minio.example.com}`)
        - traefik.http.routers.minio.service=minio
        - traefik.http.routers.minio.tls.certresolver=letsencrypt
        - traefik.http.routers.minio.tls=true
        - traefik.http.services.minio.loadbalancer.server.port=9000
        - traefik.http.routers.minio-console.entrypoints=websecure
        - traefik.http.routers.minio-console.rule=Host(`${MINIO_CONSOLE_URL:-console.example.com}`)
        - traefik.http.routers.minio-console.service=minio-console
        - traefik.http.routers.minio-console.tls.certresolver=letsencrypt
        - traefik.http.routers.minio-console.tls=true
        - traefik.http.services.minio-console.loadbalancer.server.port=9001
    volumes:
      - ${MINIO_BIND:-./minio}:/data
    command: server /data --console-address ":9001"
    networks:
      - traefik-public
    environment:
      MINIO_BROWSER_REDIRECT_URL: https://${MINIO_CONSOLE_URL:-console.example.com}
      MINIO_ROOT_USER: ${MINIO_USER:-notminioadmin}
      MINIO_ROOT_PASSWORD: ${MINIO_PASSWORD:-changeme}

networks:
  traefik-public:
    external: true